#!/bin/sh
# vim: set ft=sh

set -e -u

source $(dirname $0)/common.sh

# for jq
PATH=/usr/local/bin:$PATH

load_pubkey $REQUEST

uri=$(jq -r '.source.uri // ""' < $REQUEST)
branch=$(jq -r '.source.branch // ""' < $REQUEST)
paths="$(jq -r '(.source.paths // ["."])[]' < $REQUEST)" # those "'s are important
ignore_paths="$(jq -r '":!" + (.source.ignore_paths // [])[]' < $REQUEST)" # these ones too
ref=$(jq -r '.version.ref // ""' < $REQUEST)

destination=$TMPDIR/git-resource-repo-cache

if [ -d $destination ]; then
  cd $destination
  git pull --ff-only
else
  branchflag=""
  if [ -n "$branch" ]; then
    branchflag="--branch $branch"
  fi

  git clone $uri $branchflag $destination
  cd $destination
fi

{
  if [ -n "$ref" ] && git cat-file -e "$ref"; then
    git log --reverse ${ref}..HEAD --pretty='format:%H' -- $paths $ignore_paths
  else
    git log -1 --pretty='format:%H' -- $paths $ignore_paths
  fi
} | jq -R '.' | jq -s "map({ref: .})" > $RESPONSE
