#!/bin/sh
# vim: set ft=sh

set -e -u

source $(dirname $0)/common.sh

# for jq
PATH=/usr/local/bin:$PATH

load_pubkey $REQUEST

uri=$(jq -r '.source.uri // ""' < $REQUEST)
branch=$(jq -r '.source.branch // ""' < $REQUEST)
ref=$(jq -r '.version.ref // "HEAD"' < $REQUEST)
fetch=$(jq -r '(.params.fetch // [])[]' < $REQUEST)
submodules=$(jq -r '(.params.submodules // "all")' < $REQUEST)

if [ -z "$uri" ]; then
  echo "invalid source configuration; missing uri" >&2
  exit 1
fi

branchflag=""
if [ -n "$branch" ]; then
  branchflag="--branch $branch"
fi

git clone $uri $branchflag $DESTINATION

cd $DESTINATION

git checkout -q $ref
git log -1 --oneline
git clean --force --force -d

if [ "$submodules" == "all" ]; then
  git submodule update --init --recursive
elif [ "$submodules" != "none" ]; then
  submodules=$(echo $submodules | jq -r '(.[])')
  for submodule in $submodules; do
    git submodule update --init --recursive $submodule
  done
fi

for branch in $fetch; do
  git fetch origin $branch
  git branch $branch FETCH_HEAD
done

jq -n "{
  version: {ref: $(git rev-parse HEAD | jq -R .)},
  metadata: $(git_metadata)
}" > $RESPONSE
